### ISSUE TITLE
Stopped working recently 

### ISSUE THREAD

**Issue by M0nero** [lol219/NitroFlex#3]
![image](https://user-images.githubusercontent.com/70347351/151621285-ab36f5be-e2de-42e3-96bf-64c4e49bdb58.png)

**Comment by lol219** [comment]
@M0nero Are you sure that it doesn't work , try enable 1080 bypass in plugin settings , if it was enabled , re-enable it then it should work.

**Comment by lol219** [comment]
@M0nero If you don't mind , can you please join my support server to discuss about it ? thanks
**Support Server Link** 
https://discord.gg/TCuGtFNhpq

**Comment by lol219** [comment]
@M0nero Thanks for reaching us, please update your nitroflex ,and please remove your ZerePluginLibrary then replace it with this modified one https://raw.githubusercontent.com/BlackusPL/OnesPluginLibrary/main/0PluginLibrary.plugin.js
because the original one is broken so that's why nitroflex is broken 
Goodbye !

**Comment by lol219** [comment]
Hmm, did it break again

**Comment by M0nero** [comment]
e

**Comment by lol219** [comment]
e
